require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - config/puma.rb
    - db/**/*
    - spec/spec_helper.rb

  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false
