inherit_from: ../.rubocop.yml

Layout/LineLength:
  Max: 200

Metrics/BlockLength:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 10

Style/OpenStructUse:
  Enabled: false
