---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/games/{game_uuid}/attempts":
    post:
      summary: Create a new attempt for the current word of the current game
      tags:
      - Attempts
      description: 'TBD

        '
      parameters:
      - name: game_uuid
        in: path
        description: UUID of the game
        example: sOqmDethcUawYzhIprwk
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Attempt Registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  game:
                    type: object
                    description: State of the game
                    properties:
                      score:
                        type: integer
                        example: 42
                        description: Score (if game is done)
                      status:
                        type: string
                        example: done
                        description: Status of the word currently being played
                      current_word:
                        type: object
                        properties:
                          status:
                            type: string
                            example: done
                            description: DONE|ONGOING
                          success:
                            type: boolean
                            example: true
                            description: Wether or not you've won the word
                          attempts:
                            type: array
                            description: List of attempts for the given word so far
                              (most recent last)
                            items:
                              type: object
                              properties:
                                guess:
                                  type: string
                                  example: sword
                                  description: Guess submitted in the API call
                                letters:
                                  type: array
                                  description: List of letters in the latest guess
                                    and their result
                                  items:
                                    type: object
                                    properties:
                                      letter:
                                        type: string
                                        example: s
                                        description: Letter that was guessed for given
                                          position
                                      result:
                                        type: string
                                        example: wrong_position
                                        description: Result for that letter
                                    required:
                                    - letter
                                    - result
                              required:
                              - guess
                              - letters
                        required:
                        - status
                        - success
                        - attempts
                    required:
                    - status
                    - current_word
                required:
                - game
        '422':
          description: Invalid guess
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    description: Info about the errors
                required:
                - errors
      requestBody:
        content:
          application/json:
            schema:
              properties:
                attempt:
                  type: object
                  description: New attempt for the current word of the current game
                  properties:
                    guess:
                      description: Your guess
                      example: sword
                      type: string
                  required:
                  - guess
              required:
              - attempt
  "/games":
    post:
      summary: Create a new game
      tags:
      - Games
      description: |
        This endpoint creates a new game.
        If no parameters are given, the following configuration is used:
        * 25 words to guess
        * words are 5 letters long
        * you get 6 attempts per words

        If you improved your guessing program and want to replay a past game,
        save the seed from that game and reuse it when creating a new one!
      parameters: []
      responses:
        '201':
          description: game created
          content:
            application/json:
              schema:
                type: object
                properties:
                  game:
                    type: object
                    description: Game object with configuration
                    properties:
                      uuid:
                        description: UUID of your game, use that to play!
                        example: sOqmDethcUawYzhIprwk.
                        type: string
                      seed:
                        description: Seed used to generate the word list, use that
                          to play the same game again
                        example: LMdflkdSrlcz6RkO2OFvfQ==
                        type: string
                      max_attempts:
                        description: Number of attempts to guess each word
                        example: 6
                        type: integer
                      max_words:
                        description: Number of words to guess
                        example: 25
                        type: integer
                      word_length:
                        description: Length of the words the guess
                        example: 5
                        type: integer
                    required:
                    - uuid
                    - seed
                    - max_attempts
                    - max_words
                    - word_length
                required:
                - game
      requestBody:
        content:
          application/json:
            schema:
              properties:
                game:
                  type: object
                  description: Configuration for the game
                  optional: true
                  properties:
                    max_attempts:
                      description: Number of attempts to guess each word
                      default: 6
                      minimum: 4
                      maximum: 10
                      type: int
                    max_words:
                      description: Number of words to guess
                      default: 25
                      minimum: 10
                      maximum: 50
                      type: int
                    seed:
                      description: Seed to use to generate the word list (to repeat
                        previous games)
                      type: string
                    word_length:
                      description: Length of the words the guess
                      default: 5
                      minimum: 3
                      maximum: 16
                      type: int
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
