---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/games":
    post:
      summary: Create a new game
      tags:
      - Games
      description: |
        This endpoint creates a new game.
        If no parameters are given, the following configuration is used:
        * 25 words to guess
        * words are 5 letters long
        * you get 6 attempts per words

        If you improved your guessing program and want to replay a past game,
        save the seed from that game and reuse it when creating a new one!
      parameters: []
      responses:
        '201':
          description: game created
          content:
            application/json:
              schema:
                type: object
                properties:
                  game:
                    type: object
                    description: Game object with configuration
                    properties:
                      uuid:
                        description: UUID of your game, use that to play!
                        example: sOqmDethcUawYzhIprwk.
                        type: string
                      seed:
                        description: Seed used to generate the word list, use that
                          to play the same game again
                        example: LMdflkdSrlcz6RkO2OFvfQ==
                        type: string
                      max_attempts:
                        description: Number of attempts to guess each word
                        example: 6
                        type: integer
                      max_words:
                        description: Number of words to guess
                        example: 25
                        type: integer
                      word_length:
                        description: Length of the words the guess
                        example: 5
                        type: integer
                    required:
                    - uuid
                    - seed
                    - max_attempts
                    - max_words
                    - word_length
                required:
                - game
      requestBody:
        content:
          application/json:
            schema:
              properties:
                game:
                  type: object
                  description: Configuration for the game
                  optional: true
                  properties:
                    max_attempts:
                      description: Number of attempts to guess each word
                      default: 6
                      minimum: 4
                      maximum: 10
                      type: int
                    max_words:
                      description: Number of words to guess
                      default: 25
                      minimum: 10
                      maximum: 50
                      type: int
                    seed:
                      description: Seed to use to generate the word list (to repeat
                        previous games)
                      type: string
                    word_length:
                      description: Length of the words the guess
                      default: 5
                      minimum: 3
                      maximum: 16
                      type: int
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
